### PR TITLE
Bugfix: Fix ignored `venv.in_project` config while creating venv

### LINKED ISSUE #32: pdm project config `venv.in_project` is ignored while venv creation
**Describe the bug**
As mentioned in [docs](https://pdm-project.github.io/pdm-venv/#configuration)  if pdm config `venv.in_project` is set to true, then virtual-env is created in project directory. This feature is not working while using `pdm venv create`.

**To Reproduce**
1. Go to project directory (after plugin is installed)
2. Run command `pdm config venv.in_project True` and then `pdm venv create`

**Expected behavior**
A virtual-env should have been created in the project directory.

**Current behavior**
Virtual env is getting created in the location specified under `venv.location` config

**Screenshots**
NA

**System :**
- `pdm-venv` version: 0.4.0
- Python version: 3.10 (all)
- OS: MacOS (all)

**Additional context**
As [create method](https://github.com/pdm-project/pdm-venv/blob/42dad5699c5fcc45d1cc4f9f96eed8bbc8a16e1a/src/pdm_venv/backends.py#L75) supports `in_project` argument, but it is always falling back to default value, due to in [create command](https://github.com/pdm-project/pdm-venv/blob/42dad5699c5fcc45d1cc4f9f96eed8bbc8a16e1a/src/pdm_venv/commands/create.py#L50) this argument is not passed from the project config.

### PR DESCRIPTION
**Pull request by xanterx**
### Pull Request Check List

- [x]  A news fragment is added in news/ describing what is new.
- [ ]  Test cases added for changed code.

Describe what you have changed in this PR.
Close #32

### CODE REVIEW

**Comment by frostming** [comment]
But this means the `--name` argument will be ignored and always override the existing venv.

Is this what users want?

**Comment by xanterx** [comment]
The way we are storing the name of virtual-env is storing by the value after the virtual-env path hash. ([backend.py#L68](https://github.com/pdm-project/pdm-venv/blob/42dad5699c5fcc45d1cc4f9f96eed8bbc8a16e1a/src/pdm_venv/backends.py#L68)).

Right now, if `venv.in_project` is  **true** it is creating a by default name `.venv` ([backend.py#L78](https://github.com/pdm-project/pdm-venv/blob/42dad5699c5fcc45d1cc4f9f96eed8bbc8a16e1a/src/pdm_venv/backends.py#L78)). And the default key given to this is `in-project` ([utils.py#L30](https://github.com/pdm-project/pdm-venv/blob/42dad5699c5fcc45d1cc4f9f96eed8bbc8a16e1a/src/pdm_venv/utils.py#L30)). 

If we consider overriding default in-project virtual-env name with the user supplied `--name` argument, and store the name as a part of in-project virtual-env folder name. This will override the default names used for in-project  virtual-env folders. ([pdm/utils.py#L294](https://github.com/pdm-project/pdm/blob/df1afd6e56286e255f7e642ccf4c80612dfc2a08/pdm/utils.py#L292))

Therefore, in my opinion we should ignore the `--name` argument  if `venv.in-project` config is **true**.

If you like user to still have an option and override this in-project virtual-env I can create a separate PR to update iter_venv func and also create one for pdm to recognize these names.
or 
I can update the docs for above behaviour.

**Comment by frostming** [comment]
> Therefore, in my opinion we should ignore the --name argument if venv.in-project config is true.

Maybe we can create venv in-project when `--name` isn't given.

**Comment by xanterx** [comment]
In my workflow when `--name` was not given pdm-venv created the virtual-env in the location given in `venv.location`. Which I expected it to be created. And it defaulted the name to the python version. I really liked that.
From a user experience perspective, it made sense to me, that you will get in-project venv only if you enable `venv.in_project` flag.

**Comment by frostming** [comment]
> In my workflow when `--name` was not given pdm-venv created the virtual-env in the location given in `venv.location`. Which I expected it to be created. And it defaulted the name to the python version. I really liked that. From a user experience perspective, it made sense to me, that you will get in-project venv only if you enable `venv.in_project` flag.

So can you make the change?

**Comment by xanterx** [comment]
> Maybe we can create venv in-project when `--name` isn't given.

So, you want me to make this change. 👆

>From a user experience perspective, it made sense to me, that you will get in-project venv only if you enable venv.in_project flag.
Or do you want me to keep this behaviour 👆. For this behaviour no change is needed.

**Comment by frostming** [comment]
To clarify:

venv.in-project = true and `--name` not given:  create virtualenv in project
otherwise, create under venv.location with name + hash

**Comment by xanterx** [comment]
> venv.in-project = true and --name not given: create virtualenv in project
otherwise, create under venv.location with name + hash

✅Done

**Review by frostming — APPROVED** [review]

**Pull request merged**
