### PR TITLE
add support local venv creation #20

### PR DESCRIPTION
**Pull request by jamestansx**
This pr is to add option to create virtualenv in local project dir.

Ref: #20

### CODE REVIEW

**Comment by frostming** [comment]
I think changing `venv.location` to the project root should work. And the venvs can be managed by `list`, `remove` and `purge` commands. We don't need another option.

**Comment by jamestansx** [comment]
Just that setting the `venv.location` to project root would break `purge` command.

**Comment by jamestansx** [comment]
Hi, I just have some thoughts about this. Because `venv.location` can only be set globally and not in the project, I think it would be better if `pdm-venv` can have an optional argument to create venv in the local project instead of setting it globally. Thoughts?

**Comment by frostming** [comment]
If that is the case I think it is better to allowing setting `venv.location` per project

**Comment by jamestansx** [comment]
Hi, sorry for late reply, was busy working on school projects. Following your reply, I think I will close this PR and open a new one (if needed).

**Pull request closed without merging**
